In [ ]:
# Working with Missing Data in Pandas
# Missing Data can occur when no information is provided for one or more
# items or for a whole unit. Missing Data is a very big problem in a real-life scenarios.
# Missing Data can also refer to as NA ( Not Available ) values in pandas.
# In DataFrame sometimes many datasets simply arrive with missing data,
# either because it exists and was not collected or it never existed.
# For Example, Suppose different users being surveyed may choose not to share their income,
# some users may choose not to share the address in this way many datasets went missing.

# Dataset 1 : https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv
# Dataset 2 : https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

ufo = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
ufo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             18215 non-null  object
 1   Colors Reported  2882 non-null   object
 2   Shape Reported   15597 non-null  object
 3   State            18241 non-null  object
 4   Time             18241 non-null  object
dtypes: object(5)
memory usage: 712.7+ KB

In [ ]:
ufo.isnull().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [ ]:
# Remove missing values
# dropna()
ufo.dropna().shape

(2486, 5)

In [ ]:
# Fill NA/NaN using specified method
# fillna()

ufo['City'].fillna(value='CityNotMentioned',inplace=True)
ufo['Colors Reported'].fillna(value='Unknown',inplace=True)
ufo['Shape Reported'].fillna(value='NotDefined',inplace=True)

In [ ]:
ufo.isnull().sum()

City               0
Colors Reported    0
Shape Reported     0
State              0
Time               0
dtype: int64

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          7 non-null      int64
 1   Name        7 non-null      object
 2   Marks       5 non-null      float64
 3   Percentage  3 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 356.0+ bytes

In [ ]:
data.isnull().sum()

Id            0
Name          0
Marks         2
Percentage    4
dtype: int64

In [ ]:
data['Marks'].fillna(method='bfill',inplace=True)

In [ ]:
data['Percentage'].fillna(method='ffill',inplace=True)

In [ ]:
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        78.0
2   3  Alex   12.0        67.0
3   4  Alex   12.0        67.0
4   5  Alex   54.0        67.0
5   6  Alex   54.0        67.0
6   7  Alex   65.0        66.0

In [ ]:
# Fill Missing Values By Taking Up A Mean
data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
mean_marks = data['Marks'].mean()
data['Marks'].fillna(value=mean_marks,inplace=True)
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex   46.4        67.0
3   4  Alex   12.0         NaN
4   5  Alex   46.4         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
mean_per = data['Percentage'].mean()
mean_per = round(mean_per,1)
data['Percentage'].fillna(value=mean_per,inplace=True)
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        70.3
2   3  Alex   46.4        67.0
3   4  Alex   12.0        70.3
4   5  Alex   46.4        70.3
5   6  Alex   54.0        70.3
6   7  Alex   65.0        66.0

In [ ]:
# Filling missing value using interpolate()
data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [ ]:
data.interpolate()

   Id  Name  Marks  Percentage
0   1  Alex   78.0       78.00
1   2  Alex   23.0       72.50
2   3  Alex   17.5       67.00
3   4  Alex   12.0       66.75
4   5  Alex   33.0       66.50
5   6  Alex   54.0       66.25
6   7  Alex   65.0       66.00

In [ ]:
# Remove Duplicate Records
# Handle Duplicate Data
# Dealing With Duplicate Data

# Create a DataFrame
data = {
    'StudentName':['Mark','Ali','Bob','John','Johny','Mark'],
    'Score':[45,65,76,44,39,45]
}
df = pd.DataFrame(data)
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45

In [ ]:
# Check duplicate records
print(df.duplicated().sum())

1

In [ ]:
df[df.duplicated()]

  StudentName  Score
5        Mark     45

In [ ]:
df[df['StudentName']=='Mark']

  StudentName  Score
0        Mark     45
5        Mark     45

In [ ]:
# Dropping duplicates
df.drop_duplicates(inplace=True)

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
data = {
    'StudentName':['Mark','Ali','Bob','John','Johny','Mark'],
    'Score':[45,65,76,44,39,45]
}
df = pd.DataFrame(data)
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45

In [ ]:
# Keep last duplicate
df.drop_duplicates(keep='last',inplace=True)
df

  StudentName  Score
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45