In [ ]:
# Data Science Library --> PANDAS
import numpy as np
import pandas as pd

In [ ]:
# numpy --> array()
arr = np.array([10,20,30,40])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]

In [ ]:
# PANDAS
# - Series (1D Array)
# - DataFrame (2D Array)

In [ ]:
# PANDAS (SERIES)
# Series is 1D Labelled Array
# Series is like Dictionary + Array combo

s = pd.Series([10,20,30,40])
print(type(s))
print(s)
print(s.shape)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
dtype: int64
(4,)

In [ ]:
# In NumPy array we cannot store mixed data types
arr = np.array([123,'John',4500.32,True])
print(arr)

['123' 'John' '4500.32' 'True']

In [ ]:
s = pd.Series([123,'John',4500.32,True])
print(s)
print(s.values)

0        123
1       John
2    4500.32
3       True
dtype: object
[123 'John' 4500.32 True]

In [ ]:
s = pd.Series([123,'John',4500.32,True], index = ['id','name','sal','status'])
print(s)
print(s['sal'])

#   123   'John'   4500.32    True
#    0      1        2         3
#   id     name     sal       status

# If you want to get Data Value by using Index Number use iloc [Index Location]
print(s.iloc[3])

# get() --> build-in function

print(s.get('name'))

id            123
name         John
sal       4500.32
status       True
dtype: object
4500.32
True
John

In [ ]:
# Indexing / Slicing / For Loop

s = pd.Series([123,'John',4500.32,True], index = ['id','name','sal','status'])
print(s)

#   123   'John'   4500.32    True
#    0      1        2         3
#   id     name     sal       status

# Indexing in Series can be done by using [], loc[] or iloc[]

print('\nIndexing In Series')

print(s['sal'])          # [] for Labels
print(s.loc['name'])     # loc[] for Labels
print(s.iloc[3])         # iloc[] for indexNumbers

print('\nSlicing In Series')
print(s[0:3])              # 3 will be excluded (stopIndex)
print(s['name':'status'])  # if using Labels, end label included

print('\nPrinting Specific Info In Series')
print(s[['id','name','status']])   # s[['LabelName','LabelName']]
print(s[['id','name','status']].values)

id            123
name         John
sal       4500.32
status       True
dtype: object

Indexing In Series
4500.32
John
True

Slicing In Series
id          123
name       John
sal     4500.32
dtype: object
name         John
sal       4500.32
status       True
dtype: object

Printing Specific Info In Series
id         123
name      John
status    True
dtype: object
[123 'John' True]

In [ ]:
# Using For Loop
for i in s:
  print(i)

123
John
4500.32
True

In [ ]:
for i in s.items():
  print(i)

('id', 123)
('name', 'John')
('sal', 4500.32)
('status', True)

In [ ]:
for k,v in s.items():
  print(k,v)

id 123
name John
sal 4500.32
status True

In [ ]:
# Pandas DataFrame
# It's a 2D array
# It is used to display information in tabular fashion

data = {
    'name' : ['John','Smith','Alex','Mathews'],
    'dept' : ['IT','Marketing','Sales','Finance'],
    'salary' : [7800,6700,5500,8000],
    'city' : ['KL','Klang','Melaka','Johor']
}
print(data)

{'name': ['John', 'Smith', 'Alex', 'Mathews'], 'dept': ['IT', 'Marketing', 'Sales', 'Finance'], 'salary': [7800, 6700, 5500, 8000], 'city': ['KL', 'Klang', 'Melaka', 'Johor']}

In [ ]:
df = pd.DataFrame(data)
df

      name       dept  salary    city
0     John         IT    7800      KL
1    Smith  Marketing    6700   Klang
2     Alex      Sales    5500  Melaka
3  Mathews    Finance    8000   Johor

In [ ]:
print(df.shape)

(4, 4)

In [ ]:
data = {
    'Calories':[420,380,560],
    'Duration':[56,30,75]
}
df = pd.DataFrame(data,index=['Day1','Day2','Day3'])
df

      Calories  Duration
Day1       420        56
Day2       380        30
Day3       560        75

In [ ]:
df['Calories']

Day1    420
Day2    380
Day3    560
Name: Calories, dtype: int64

In [ ]:
print(df['Calories'].values)

[420 380 560]

In [ ]:
df.loc['Day1']

Calories    420
Duration     56
Name: Day1, dtype: int64

In [ ]:
df.loc[['Day1','Day3']]

      Calories  Duration
Day1       420        56
Day3       560        75

In [ ]:
df['Duration']>50

Day1     True
Day2    False
Day3     True
Name: Duration, dtype: bool

In [ ]:
df[df['Duration']>50]

      Calories  Duration
Day1       420        56
Day3       560        75